# Generated by Django 5.2.6 on 2025-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zingmind", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
