# Generated by Django 5.2.6 on 2025-10-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zingmind", "0002_alter_adminuser_options_alter_adminuser_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(
                        default="profile_images/default.png",
                        upload_to="profile_images/",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AdminUser",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
