# Generated by Django 5.2.6 on 2025-10-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zingmind", "0003_admin_employees_delete_adminuser_delete_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "assets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(blank=True, null=True)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "attendance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeAppraisals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appraisal_period",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "self_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "manager_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("appraisal_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_appraisals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("condition_on_return", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_assets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                ("account_no", models.CharField(blank=True, max_length=50, null=True)),
                ("ifsc", models.CharField(blank=True, max_length=20, null=True)),
                ("pan", models.CharField(blank=True, max_length=20, null=True)),
                ("aadhar", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "employee_bank_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeContacts",
            fields=[
                (
                    "employee_code",
                    models.OneToOneField(
                        db_column="employee_code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="zingmind.employees",
                    ),
                ),
                ("mobile_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "alternate_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("contact_no", models.CharField(blank=True, max_length=15, null=True)),
                ("permanent_address", models.TextField(blank=True, null=True)),
                ("present_address", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
            options={
                "db_table": "employee_contacts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_description", models.TextField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_goals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_leaves",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeePersonalInfo",
            fields=[
                (
                    "employee_code",
                    models.OneToOneField(
                        db_column="employee_code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="zingmind.employees",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "functional_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                ("work_history", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_personal_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "leave_types",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "annual_ctc_without_bonus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_ctc_with_bonus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "basic_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "conveyance_allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "medical_allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "telephone_reimbursement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "uniform_allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bonus_eligible", models.IntegerField(blank=True, null=True)),
                (
                    "revision_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_revision_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "salary_structure",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_year", models.CharField(blank=True, max_length=10, null=True)),
                ("total_days", models.IntegerField(blank=True, null=True)),
                ("working_days", models.IntegerField(blank=True, null=True)),
                (
                    "gross_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "advance_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "leave_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "professional_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employee_pf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "esic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_monthly_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "inhand_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employer_epf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employer_esic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bonus_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "salary_transactions",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.RemoveField(
            model_name="document",
            name="company",
        ),
        migrations.AlterModelOptions(
            name="employees",
            options={"managed": False},
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
